### ISSUE TITLE
Connect to Spotify Artists endpoint

### ISSUE THREAD

**Issue by radualex** [Craners/mumble#26]
https://developer.spotify.com/documentation/web-api/reference/artists/

GET /v1/artists -- Get Several Artists. - for genres
GET /v1/artists/{id}/related-artists - Get an Artist's related artists. (MVP 2.0)

**Comment by codacy20** [comment]
this issue is expanding:
- you should retrieve all the songs in history based on the time span. (this function can be reused for the history page)
- you should be able to calculate the percentage/number of times in which a genre was repeated.
